### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by designosis** [julien-maurel/eedomus-scripts#1]
Hi Julien!

You wrote some jQuery Scanner Detection code in 2013 (https://plugins.jquery.com/scannerdetection/), but no longer have the github repository online. Is 1.1.4 your latest version?

Edit: I found what looks like a copy of version 1.2 at https://github.com/lucasjahn/jQuery-Scanner-Detection/ ... so maybe 1.2 is the best version?

Thanks!

**Comment by julien-maurel** [comment]
Hi, yes it's the last version. I don't remember why I removed it. I think you can find some forks.
